name: Tests

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  full-test:
    uses: IMIO/gha-workflows/.github/workflows/package-full-test.yml@v1
    secrets:
      mattermost_webhook_url: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}
    with:
      check_path: |
        library/policy
      coverage_python_version: '3.12'
      python_versions: '["3.12"]'
      runner_label: gha-runners-smartweb
      upload_to_coveralls: true
